name: gura
description: A simple to use library for reading/writing Gura configuration files.
version: 1.0.4
homepage: https://gura.netlify.app/
repository: https://github.com/zajrik/gura-dart-parser
issue_tracker: https://github.com/zajrik/gura-dart-parser/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.17.9

dependencies:
  path: ^1.8.0
  tuple: ^2.0.0
