name: gura
description: A library for parsing Gura configuration files
version: 1.0.0
homepage: https://gura.netlify.app/

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0

dependencies:
  path: ^1.8.0
  tuple: ^2.0.0
  test: ^1.17.9
